MathSeer.UI/Areas/Auth/Models/UserLogin.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MathSeer.UI.Models
{
    public class UserLogin
    {
        public string Username { get; set; }

        public string Password { get; set; }
    }
}

MathSeer.UI/Areas/Auth/Models/UserRegister.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MathSeer.UI.Models
{
    public class UserRegister
    {
        public string Username { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
    }
}

MathSeer.UI/Models/ErrorViewModel.cs
using System;

namespace MathSeerUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MathSeer.UI/Areas/Auth/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MathSeer.UI.Models;
using Microsoft.AspNetCore.Mvc;

namespace MathSeer.UI.Controllers
{
    [Route("/auth")]
    public class AuthController : Controller
    {
        [Route("login")]
        public IActionResult UserLogin()
        {
            return View(new UserLogin());
        }

        public void SignIn()
        {
            return;
        }

        [Route("register")]
        public IActionResult UserRegister()
        {
            return View(new UserRegister());
        }

        public void CreateUser(UserRegister newUser)
        {
            return;
        }

    }
}

MathSeer.UI/Areas/Math/Controllers/AlgebraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MathSeer.UI.Areas.Math.Controllers
{
    [Route("/algebra")]
    public class AlgebraController : Controller
    {
        [Route("/")]
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Editor()
        {
            return View();
        }

        public IActionResult Answersheet()
        {
            return View();
        }
    }
}

MathSeer.UI/Areas/Math/Controllers/GraphController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MathSeer.UI.Areas.Math.Controllers
{
    [Route("/graphs")]
    public class GraphController : Controller
    {
        [Route("/")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

MathSeer.UI/Areas/Math/Controllers/TrigController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MathSeer.UI.Areas.Math.Controllers
{
    [Route("/trigs")]
    public class TrigController : Controller
    {
        [Route("/")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

MathSeer.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MathSeerUI.Models;

namespace MathSeerUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MathSeer.UI/Controllers/MathController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MathSeer.UI.Controllers
{
    [Route("/math")]
    public class MathController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet, Route("/algebra")]
        public IActionResult Algebra()
        {
            return View();
        }

        [HttpGet, Route("/trigs")]
        public IActionResult Trig()
        {
            return View();
        }
    }
}

MathSeer.UI/Areas/Math/Views/Algebra/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

MathSeer.UI/Areas/Math/Views/Graphs/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

MathSeer.UI/Areas/Math/Views/Trigs/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

MathSeer.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MathSeer.UI/Views/Math/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div>
    <h2>
        Welcome to Math
    </h2>

    <div>
        <ul>
            <li>Algebra</li>
            <li>Trigonometry</li>
            <li>Pre-Calculus</li>
        </ul>
    </div>
</div>

MathSeer.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <base href="~/" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MathSeer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MathSeerUI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Math" asp-action="Index">Math</a>
                        </li>
                        <li class="nav-item float-right">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item float-right">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MathSeerUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>